use_frameworks!

target 'KNPodlib_Example' do
  pod 'KNPodlib', :path => '../'

  target 'KNPodlib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
