use_frameworks!
#cd Example ;执行pod install，让demo项目安装依赖项并更新配置
#pod install --no-repo-update
target 'KNPodlib_Example' do
  pod 'KNPodlib', :path => '../'

  target 'KNPodlib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
#    Would you like to do view based testing? [ Yes / No ]
#    > Yes： using FBSnapShotTestCase, if you are using Specta/Expecta then we include a Pod to improve the syntax
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
